### ISSUE TITLE
Certificate validation error on OS X

### ISSUE THREAD

**Issue by ketys** [italiangrid/voms-clients#17]
Hello :)

I would like to run voms on my OS X laptop, but I'm facing a problem which I'm not able to solve :( I've installed everything on Ubuntu 14.04 in VirtualBox and there it works! -> voms-proxy-init -voms <url> --rfc contacts the remote VOMS server and create a proxy. But on my OS X it throws the following errors after passing the GRID phrase for identity:

```
Certificate validation error: No trusted CA certificate was found for the certificate chain
Certificate validation error: Trusted issuer of this certificate was not established
User credential is not valid!
```

Could you tell me, what's wrong? :) Thank you very much!

**Comment by andreaceccanti** [comment]
Hello.
I guess you're missing the CA certificates in /etc/grid-security/certificates. Do you have such directory in your OS X machine?

**Comment by ketys** [comment]
Yes, I have this directory also on OS X machine, but I've found (maybe) a problem. If I compare the files (with Ubuntu machine), I'm missing `TERENAeSciencePersonal*`, there's only `TERENA-eScience-SSL-*`. What causes this problem? I tried to copy files from Ubuntu to Mac, but it din't work.

**Comment by andreaceccanti** [comment]
Strange. Make sure the /etc/grid-security/certficates directory contents are the same. Things work 
fine for me on OS X.

**Comment by lezzidan** [comment]
Hi,
I'm having the same problem on OSX, I have all the certificates installed.

Daniele

**Comment by lezzidan** [comment]
More details: the proxy is properly created if I don't specify the VO, so with no voms extensions

**Comment by andreaceccanti** [comment]
Please run voms-proxy-init with --debug and attach the output to this issue

**Comment by lezzidan** [comment]
I solved the issue. I was using a Terena Personal CA certificate which is not accepted by EGI Fed Cloud. I had to get a new certificate from Terena eScience personal CA. So, it was an error returned by the VOMS server, not a local one from the client. 
Thanks

**Comment by andreaceccanti** [comment]
ok, closing this issue then

**Comment by ketys** [comment]
I'm still getting this:

```
voms-proxy-init -voms fedcloud.egi.eu --rfc --debug
Looking for VOMS AA certificates in /etc/grid-security/vomsdir...
Looking for LSC information in /etc/grid-security/vomsdir/fedcloud.egi.eu...
Loaded LSC information from file /etc/grid-security/vomsdir/fedcloud.egi.eu/voms1.grid.cesnet.cz.lsc: LSCFile [filename=/etc/grid-security/vomsdir/fedcloud.egi.eu/voms1.grid.cesnet.cz.lsc, vo=fedcloud.egi.eu, hostname=voms1.grid.cesnet.cz, certChainDescription=[/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms1.grid.cesnet.cz, /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience SSL CA 3]]
Loaded LSC information from file /etc/grid-security/vomsdir/fedcloud.egi.eu/voms2.grid.cesnet.cz.lsc: LSCFile [filename=/etc/grid-security/vomsdir/fedcloud.egi.eu/voms2.grid.cesnet.cz.lsc, vo=fedcloud.egi.eu, hostname=voms2.grid.cesnet.cz, certChainDescription=[/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms2.grid.cesnet.cz, /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience SSL CA 3]]
Looking for VOMS AA certificates in /etc/grid-security/vomsdir/fedcloud.egi.eu...
Looking for LSC information in /etc/grid-security/vomsdir/training.egi.eu...
Loaded LSC information from file /etc/grid-security/vomsdir/training.egi.eu/voms1.grid.cesnet.cz.lsc: LSCFile [filename=/etc/grid-security/vomsdir/training.egi.eu/voms1.grid.cesnet.cz.lsc, vo=training.egi.eu, hostname=voms1.grid.cesnet.cz, certChainDescription=[/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms1.grid.cesnet.cz, /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience SSL CA 3]]
Loaded LSC information from file /etc/grid-security/vomsdir/training.egi.eu/voms2.grid.cesnet.cz.lsc: LSCFile [filename=/etc/grid-security/vomsdir/training.egi.eu/voms2.grid.cesnet.cz.lsc, vo=training.egi.eu, hostname=voms2.grid.cesnet.cz, certChainDescription=[/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms2.grid.cesnet.cz, /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience SSL CA 3]]
Looking for VOMS AA certificates in /etc/grid-security/vomsdir/training.egi.eu...
Looking for VOMSES information in /etc/vomses...
Loaded vomses information 'VOMSServerInfo [alias=fedcloud.egi.eu, voName=fedcloud.egi.eu, URL=voms://voms1.grid.cesnet.cz:15002, vomsServerDN=/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms1.grid.cesnet.cz]' from /etc/vomses.
Loaded vomses information 'VOMSServerInfo [alias=fedcloud.egi.eu, voName=fedcloud.egi.eu, URL=voms://voms2.grid.cesnet.cz:15002, vomsServerDN=/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms2.grid.cesnet.cz]' from /etc/vomses.
Looking for user credentials in [/Users/ketys/.globus/userkey.pem, /Users/ketys/.globus/usercert.pem]...
Enter GRID pass phrase for this identity:
Credentials loaded successfully [/Users/ketys/.globus/userkey.pem, /Users/ketys/.globus/usercert.pem]
Certificate validation error: No trusted CA certificate was found for the certificate chain
Certificate validation error: Trusted issuer of this certificate was not established
User credential is not valid!
org.italiangrid.voms.VOMSError: User credential is not valid!
	at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.validateUserCredential(DefaultVOMSProxyInitBehaviour.java:152)
	at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.initProxy(DefaultVOMSProxyInitBehaviour.java:192)
	at org.italiangrid.voms.clients.VomsProxyInit.execute(VomsProxyInit.java:307)
	at org.italiangrid.voms.clients.VomsProxyInit.<init>(VomsProxyInit.java:71)
	at org.italiangrid.voms.clients.VomsProxyInit.main(VomsProxyInit.java:55)
```

**Comment by andreaceccanti** [comment]
The error message is pretty clear:
```
Certificate validation error: No trusted CA certificate was found for the certificate chain
Certificate validation error: Trusted issuer of this certificate was not established
```
voms-proxy-init does not find the CA certificate that issued your personal certificate in
/etc/grid-security/certificates.

What's the output of
```
openssl x509 -in /Users/ketys/.globus/usercert.pem -noout -subject -issuer
```
